#!/bin/bash

if [ -d "_posts" ]; then
   echo "exiting, _posts already exists"
   exit 0
fi

mkdir "_posts"
echo "mkdir _posts"

for DIRECTORY in "$@" 
do
   cp "${DIRECTORY}/index.md" "_posts/2014-10-10-${DIRECTORY}.md"
   echo "cp ${DIRECTORY}/index.md _posts/2014-10-10-${DIRECTORY}.md"
done